-- Generated via `dotnet ef migrations script --idempotent` from Migrations/20260906062809_InitialCreate.
-- Reflects the schema actually applied to the database (EF Core PascalCase convention).
-- Do not hand-edit; regenerate from EF migrations if the model changes.

CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260906062809_InitialCreate') THEN
    CREATE TABLE "Clients" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Name" text NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL DEFAULT (now()),
        CONSTRAINT "PK_Clients" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260906062809_InitialCreate') THEN
    CREATE TABLE "ApiKeys" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "ClientId" integer NOT NULL,
        "KeyHash" text NOT NULL,
        "Status" text NOT NULL DEFAULT 'active',
        "CreatedAt" timestamp with time zone NOT NULL DEFAULT (now()),
        CONSTRAINT "PK_ApiKeys" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_ApiKeys_Clients_ClientId" FOREIGN KEY ("ClientId") REFERENCES "Clients" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260906062809_InitialCreate') THEN
    CREATE INDEX "IX_ApiKeys_ClientId" ON "ApiKeys" ("ClientId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260906062809_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_ApiKeys_KeyHash" ON "ApiKeys" ("KeyHash");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260906062809_InitialCreate') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260906062809_InitialCreate', '8.0.11');
    END IF;
END $EF$;
COMMIT;
