-- Generated via `dotnet ef migrations script AddClientIdentifierToClients --idempotent` from Migrations/20260906111212_AddEndUsers.
-- Adds EndUsers: an iCloud account registered by a Client, with AES-256-GCM-encrypted credentials.
-- Do not hand-edit; regenerate from EF migrations if the model changes.

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260906111212_AddEndUsers') THEN
    CREATE TABLE "EndUsers" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "ClientId" integer NOT NULL,
        "EndUserIdentifier" uuid NOT NULL DEFAULT (gen_random_uuid()),
        "IcloudEmail" text NOT NULL,
        "EncryptedPassword" text NOT NULL,
        "EncryptionIv" text NOT NULL,
        "EncryptionAuthTag" text NOT NULL,
        "CalendarName" text NOT NULL,
        "Status" text NOT NULL DEFAULT 'connected',
        "CreatedAt" timestamp with time zone NOT NULL DEFAULT (now()),
        CONSTRAINT "PK_EndUsers" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_EndUsers_Clients_ClientId" FOREIGN KEY ("ClientId") REFERENCES "Clients" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260906111212_AddEndUsers') THEN
    CREATE INDEX "IX_EndUsers_ClientId" ON "EndUsers" ("ClientId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260906111212_AddEndUsers') THEN
    CREATE UNIQUE INDEX "IX_EndUsers_EndUserIdentifier" ON "EndUsers" ("EndUserIdentifier");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260906111212_AddEndUsers') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260906111212_AddEndUsers', '8.0.11');
    END IF;
END $EF$;
COMMIT;
